config/routes.rb
Rails.application.routes.draw do

    root :to =>'foods#index'


    resources:foods do
      resources:calories

    end

    resources:exercises do
      resources:calories

    end

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'


    get '/signup' => 'users#new'
    post '/users' => 'users#create'



end

app/models/calory.rb
class Calory< ActiveRecord::Base
  belongs_to :food
  belongs_to :exercise

  validates :amount, :presence => true
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
    has_many :calories
  validates :description, :presence => true
end

app/models/food.rb
class Food < ActiveRecord::Base
    has_many :calories
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
 helper_method :current_user

 def authorize
   redirect_to '/login' unless current_user
 end


end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController
  def new
    @food = Food.find(params[:food_id])
    @exercise = Exercise.find(params[:exercise_id])
    @calory = @food.calories.new
    @calory = @exercise.calories.new
  end

  def create
      @food = Food.find(params[:food_id])
      @exercise = Exercise.find(params[:exercise_id])
      @calory = @food.calories.new(calory_params)
      @calory = @exercise.calories.new(calory_params)
      if @calory.save
          flash[:notice] = "Calories successfully added!"
        redirect_to food_path(@calory.food)
      else
        render :new
      end
    end

  private
    def task_params
      params.require(:task).permit(:description)
    end




end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def edit
   @exercise = Exercise.find(params[:id])
 end

 def update
    @exercise= Exercise.find(params[:id])
    if @exercise.update(list_params)
      redirect_to exercises_path
    else
      render :edit
    end
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
        flash[:notice] = "Exercise successfully added!"
      redirect_to  exercises_path
    else
      render :new
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    redirect_to exercises_path
  end

  private
  def exercise_params
    params.require(:exercise).permit(:description)
  end





end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all
    @food = Food.new
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
     @food = Food.new
   end

   def edit
     @food = Food.find(params[:id])
   end

   def update
     @food= Food.find(params[:id])
     if @food.update(list_params)
       redirect_to foods_path
     else
       render :edit
     end
   end


  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to  foods_path
      flash[:notice] = "New food successfully added!"
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

private
def food_params
  params.require(:food).permit(:name)
end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
      user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
    end

    def create
      user = User.new(user_params)
        if user.save
           session[:user_id] = user.id
            redirect_to '/'
        else
            redirect_to '/signup'
        end
    end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calories/_form.html.erb
<%= render('layouts/errors', :object => @calory) %>

<%= form_for [@food, @task] do |f| %>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <p><%= f.submit %></p>
<% end %>

app/views/calories/_formexercise.html.erb
<%= render('layouts/errors', :object => @calory) %>


<%= form_for [@exercise, @task] do |f| %>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <p><%= f.submit %></p>
<% end %>

app/views/calories/new.html.erb
<h1>New calories for <%= @food.name %> </h1>

<%= render 'form' %>

<h1>New calories for <%= @exercise.description %> </h1>

<%= render 'formexercise' %>

app/views/exercises/_form.html.erb
<%= render "layouts/errors", :object => @exercise %>

<%= form_for @exercise do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/exercises/edit.html.erb
<h1>Edit exercise</h1>

<%= render "form" %>

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<ul>
  <% @exercises.each do |exercise| %>
    <li><%=  link_to exercise.description, exercise_path(exercise) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Exercise", new_exercise_path %>

app/views/exercises/new.html.erb
<h1>Add new exercise</h1>

<%= render "form" %>

app/views/exercises/show.html.erb
<h1><%= @exercise.description %></h1>

<p><%= link_to "Return to exercises", exercises_path %></p>

<p><%= link_to "Edit", edit_exercise_path(@exercise) %></p>
<p><%= link_to "Delete", exercise_path(@exercise),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

app/views/foods/_form.html.erb
<%= render "layouts/errors", :object => @food %>

<%= form_for @food do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= render "form" %>

app/views/foods/index.html.erb
<% content_for(:navbar) do %>
<li><a href="/">Home</a></li>
<li><a href="foods/new">Add new food</a></li>
<% end %>

<h1>Health Tracker Deluxe-for the insecure among us</h1>

<ul>
  <% @foods.each do |food| %>
    <li><%= link_to food.name, food_path(food) %></li>
  <% end %>
</ul>
<hr>

<%= link_to "Add New Food", new_food_path %>

app/views/foods/new.html.erb
<% content_for(:navbar) do %>
<li><a href="/">Home</a></li>
<li><a href="foods/new">Add new food</a></li>
<% end %>

<h1>Enter new food</h1>

<%= render "form" %>

app/views/foods/show.html.erb
<% content_for(:navbar) do %>
<li><a href="/">Home</a></li>
<li><a href="foods/new">Add new food</a></li>
<% end %>


<h2><%= @food.name %></h2>

<% if @food.calories.any? %>
  <h4>Calories of this food:</h4>

  <ul>
    <% @food.calrories.each do |calory| %>
      <li>
        <%= calory.amount %> |
        <%= link_to "Edit", edit_food_calory_path(@food, calory) %> |
        <%= link_to "Delete", food_calory_path(@food, calory),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no calories yet!</p>
<% end %>

<br>

<p><%= link_to "Add calories", new_food_calory_path(@food) %></p>
<p><%= link_to "Delete Food", food_path(@food),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to foods", foods_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- #navbar -->
<%= yield(:navbar) %>


<!-- #flash-alerts -->
<%= flash[:alert] %>
<%= flash[:notice] %>

<br>


<!-- #user-authentication -->
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<br>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Signup yo!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>